### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by lamya3** [LukeOnuke/pvp-toggle#9]
## env: 
LeavesMC 1.20.1 [build #102](https://leavesmc.org/downloads/all)
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Zulu21.36+17-CA (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Zulu21.36+17-CA (build 21.0.4+7-LTS, mixed mode, sharing)
PVPToggle v1.4.2 (#7 ?)

## console output
```
[10:27:07 ERROR]: Could not pass event EntityDamageByEntityEvent to PVPToggle v1.4.2
java.lang.NoSuchMethodError: 'org.bukkit.damage.DamageSource org.bukkit.event.entity.EntityDamageByEntityEvent.getDamageSource()'
        at com.lukeonuke.pvptoggle.event.OnDamageListener.onHit(OnDamageListener.java:82) ~[pvp-toggle-1.4.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor345.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:53) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:264) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1037) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1014) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1249) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2208) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1061) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1439) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:968) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1138) ~[?:?]
        at net.minecraft.world.level.Explosion.explode(Explosion.java:262) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.world.level.Level.explode(Level.java:1076) ~[?:?]
        at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1870) ~[?:?]
        at net.minecraft.world.level.Level.explode(Level.java:1042) ~[?:?]
        at net.minecraft.world.entity.monster.Creeper.explodeCreeper(Creeper.java:275) ~[?:?]
        at net.minecraft.world.entity.monster.Creeper.tick(Creeper.java:162) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1350) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:860) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:837) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1568) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:456) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:27:21 ERROR]: Could not pass event EntityDamageByEntityEvent to PVPToggle v1.4.2
java.lang.NoSuchMethodError: 'org.bukkit.damage.DamageSource org.bukkit.event.entity.EntityDamageByEntityEvent.getDamageSource()'
        at com.lukeonuke.pvptoggle.event.OnDamageListener.onHit(OnDamageListener.java:82) ~[pvp-toggle-1.4.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor345.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:53) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:264) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1215) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1070) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1014) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1249) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2208) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1061) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1439) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:968) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1138) ~[?:?]
        at net.minecraft.world.entity.Mob.doHurtTarget(Mob.java:1674) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.checkAndPerformAttack(MeleeAttackGoal.java:130) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:121) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:154) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:918) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3375) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:675) ~[?:?]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:?]
        at net.minecraft.world.entity.monster.EnderMan.aiStep(EnderMan.java:280) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3030) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:437) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1350) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:860) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:837) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1568) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:456) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
## How to caused: 
console ERROR when player hit by mobs, but did't happen before use command /pvp first time (no recover even `limited-time` finished or PVP status be changed)

*bruh sorry for my poor English, but I hope these will be useful for dev*

**Comment by LukeOnuke** [comment]
I have tested out the procedure you have given me on paper 1.21.3 build no. 79, and have come to the following conclusion.

# Conclusion
The plugin `pvp-toggle` uses `EntityDamageByEntityEvent#getDamageSource().getCausingEntity()` to check for proxy attacks. Stuff like potions, projectiles and explosives. This is currently the only way of checking on who caused the proxy attack without doing some realy suspect stuff.

In conclusion, LeavesMC doesnt seem implement api method `EntityDamageByEntityEvent#getDamageSource()`.
See:
```txt
java.lang.NoSuchMethodError: 'org.bukkit.damage.DamageSource org.bukkit.event.entity.EntityDamageByEntityEvent.getDamageSource()'
        at com.lukeonuke.pvptoggle.event.OnDamageListener.onHit(OnDamageListener.java:82) ~[pvp-toggle-1.4.2.jar:?]
```

What can you do about it?
Either use the old plugin version that didn't check for who caused proxy damage and was unreliable at actually stopping proxy damage, or compile the new plugin with the proxy damage check parts removed.

---

Debating on closing the issue since that functionality is a core part of pvp-toggle, and leavesmc isn't strictly listed as supported anyways.

**Comment by lamya3** [comment]
Okay got it. thanks for your reminded and I will try it as I can

**Comment by LukeOnuke** [comment]
You can report it to the creators of LeavesMC. Hopefully they will implement the api.
